
-- 테이블 생성
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,  --값을 세팅하지 않고 넣으면 db가 알아서 값을 넣어줌
    name varchar(255),
    primary key (id)
);

SELECT * FROM MEMBER;

insert into member(name) values('spring');